# SITE CONFIGURATION
baseurl: #"/Type-on-Strap"
url: "https://doducthao.github.io"
title: Tự Học AI # site's title
description: "A blog about Math and Deep Learning" # used by search engines
markdown: kramdown
kramdown:
   math_engine: mathjax

# THEME-SPECIFIC CONFIGURATION
title: Tự Học AI  # blog's title
avatar: assets/img/dl6.jpg
favicon: assets/icons/ai1.png
gravatar: # Email MD5 hash

  # Header and footer text
header_text: > #two or three lines to describe your site
  Let's take a deep breath    
header_feature_image: assets/img/simple/simple1.png #assets/img/pexels/triangular.jpeg
footer_text: >
  I am a -.-. .... .-. .. ... - .. .- -.
excerpt: true                                        # Or "truncate" (first 250 characters), "false" to disable

color_image: /assets/img/lineart.png 

  # Scripts / Features 
google_analytics: "UA-170333390-1" # Tracking ID, e.g. "UA-000000-01"
disqus_shortname: doducthao
katex: false # Enable if using math markup
layout_variables:                                       # Open the "_sass > base" folder, and open "_variables.scss"
footer_icons: true                                        # In _data/social.yml
share_buttons: true                                         # In _data/social.yml
authors: true                                            # In _data/authors.yml
language: true
  
# special_page:
#   search: 
#     icon: "search" # Assuming page link and icon are the same
#     enabled: true
#   tags:
#     icon: "tags"
#     enabled: true

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
post_navigation: true


# PAGINATION
paginate: 10
paginate_path: "blog/page:num"


# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/:name
  math:
    output: true
    permalink: /:collection/:path/:name
  dl:
    output: true
    permalink: /:collection/:path/:name
  posts:
    output: true
    permalink: /:collection/:path/:name

math-list: [Analysis, Algebra, Probability-Statistics]
dl-list: [Neural Networks, GAN, Programming]

# BUILD SETTINGS
# markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-relative-links]
  # - jekyll-paginate
  # - jekyll-seo-tag
  # - jekyll-relative-links
# relative_links:
#   enabled:     true
#   collections: true
#theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png", "package.json", "node_modules", "gulpfile.js", ".idea/*"]
timezone: GMT+7.00 Asia/Saigon (ICT)
future: true 

